### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by LPinsight** [LPinsight/smartMirror#1]
# FRONTEND
- [x] Frontend beginnen
- [x] API im Frontend integrieren
- [x] Config Seite bauen
- [ ] Spiegel Seite bauen
- [x] get Widgets from display
- [x] add Widget to display
- [x] select Display
- [x] render Display on Change
- [x] save selected Display at backend / api
- [x] setName for new Widget
- [x] edit Display
- [x] remove Display

# BACKEND
- [x] API Display hinzufügen
- [x] Widgets entwerfen
- [x] Update Display function
